apiVersion: v1
kind: Service
metadata:
  name: cola-service
  namespace: ingress-nginx
  labels:
    app: cocacola
spec:
  selector:
    app: cocacola
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
