apiVersion: v1
kind: Service
metadata:
  name: pepsi-service
  namespace: ingress-nginx
  labels:
    app: pepsi
spec:
  selector:
    app: pepsi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
