apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cooldrinks-ingress
  namespace: ingress-nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: pepsi.cooldrinks.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pepsi-service
              port:
                number: 80
  - host: cocacola.cooldrinks.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cola-service
              port:
                number: 80

